Dev
stxreocoma/todo pull request #1
Opened 2024-09-01 19:35 UTC by stxreocoma

2024-09-02 15:14 UTC, dirtymew requested changes
Привет Глеб

хорошая работа, отлично что сделал задания со * - дал комментарии что поправить и улучшить

2024-09-02 15:14 UTC, dirtymew commented on README.md
> +Тесты можно запустить командой: go test ./tests
нужно подробнее описать что за параметры и для чего нужны

как в тестах так и для приложения

2024-09-02 15:14 UTC, dirtymew commented on README.md
> +Мой пет-проект представляет собой веб-приложение типа todo-list, разработанное с целью улучшения навыков работы с веб-технологиями и управления задачами. Этот сайт предназначен для того, чтобы помочь
отлично что дописал документацию

2024-09-02 15:14 UTC, dirtymew commented on cmd/main.go
> +package main
хороший лайаут у проекта

мб будет полезно https://github.com/golang-standards/project-layout

2024-09-02 15:14 UTC, dirtymew commented on cmd/main.go
> +	log.Println(os.Getenv("TODO_PORT"))
лучше подробнее сообщение написать при запуске

также не стоит постоянно ходить к os для переменных - стоит один раз их считать и потом использовать

2024-09-02 15:14 UTC, dirtymew commented on cmd/main.go
> +	database.ConnectGorm()
хмм ORM зло - ну ок... пусть будет

2024-09-02 15:14 UTC, dirtymew commented on database/database.go
> +func ConnectDB() {
это лишнее как я понимаю ?

2024-09-02 15:14 UTC, dirtymew commented on database/database.go
> +func ConnectDB() {
мб стоит убрать

2024-09-02 15:14 UTC, dirtymew commented on database/database.go
> +type DBinstance struct {
лучше одну структуру использовать 

посмотри в задании про посылки как там был организован сервис и сторадж

2024-09-02 15:14 UTC, dirtymew commented on dockerfile
> +FROM ubuntu:latest
файл назван не по канону - Dockerfile должен быть

2024-09-02 15:14 UTC, dirtymew commented on dockerfile
> +FROM ubuntu:latest
@stxreocoma ты наверное по заданию сделал - там не очень верно описано

не стоит хранить бинарники в репозитории - тут лучше сделать сборку приложения в докере

2024-09-02 15:14 UTC, dirtymew commented on database/database.go
> +		Gorm.Db.Exec(`CREATE TABLE scheduler (
тут явно дублирование  у тебя есть все в database/scheduler.sql

можно использовать его - например через embed

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +		pass := os.Getenv("TODO_PASSWORD")
это не хорошо делать обращения к os в запросах - один раз при старте лучше все вычитать

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +package handlers
Рекомендации по рефакторингу

 - вся логика организована в хендлерах - проект не мальнький и они уже перегружены проверками и запросами и кучей дублирующегося кода - стоит провести рефакторинг
 - по структуре проекта https://github.com/golang-standards/project-layout
 - по архитектуре - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 и в задании про посылки можно подсмотреть как организованы service и storage

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +	d, err := time.Parse("20060102", date)
20060102 в константу и везде использовать

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +	log.Println(date)
логировать все не стоит - только ошибки

ну или использовать продвинутый логгер с несколькими уровнями логирования и режим debug для работы приложения

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +	log.Println(date)
это уже за рамками курс - требовать не буде

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +	result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler WHERE id = ? LIMIT 1", id).First(&task)
ну вот а зачем gorm если ты все равно пишешь запросы руками - в чем смысл то тогда ORM использовать?

2024-09-02 15:14 UTC, dirtymew commented on models/models.go
> +type TaskForTests struct {
для тестов структуры нужно в тестах определять а не в коде

2024-09-02 15:14 UTC, dirtymew commented on tests/addtask_4_test.go
> +	log.Println(err)
зачем исправил тест - мб стоит убрать

2024-09-02 15:14 UTC, dirtymew commented on cmd/main.go
> +	app.Listen(":" + os.Getenv("TODO_PORT"))
порт бы по умолчанию из задания всетаки использовать

2024-09-02 15:14 UTC, dirtymew commented on tests/settings.go
> +var FullNextDate = true
падают часть тестов

нужно чтобы проходили - обрати внимание что бд сразу не создается - если ее нет -только при первом запросе.. но даже после этого тесты все равно падают

нужно сделать так что бы приложение пожно было запустить и сразу команда go test ./... отработала и тесты не упали - мб это подроблее с примером описать в доке

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +			result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler WHERE title LIKE ? LIMIT 50", "%"+c.Query("search")+"%").Find(&tasks)
еще и по коменту нужно искать

2024-09-02 15:14 UTC, dirtymew commented on handlers/handlers.go
> +			result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler WHERE title LIKE ? LIMIT 50", "%"+c.Query("search")+"%").Find(&tasks)
и лимит нудно вынести в константу

2024-09-02 16:20 UTC, stxreocoma commented on handlers/handlers.go
> +	result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler WHERE id = ? LIMIT 1", id).First(&task)
Gorm использовал просто чтобы попрактиковаться, запросы написаны руками так как в таблице отсутствуют нужные для gorm поля(created_at, updated_at, deleted_at), потому что с ними не проходят тесты

2024-09-02 16:57 UTC, dirtymew commented on handlers/handlers.go
> +	result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler WHERE id = ? LIMIT 1", id).First(&task)
Понятно - ну можно и тесты под это поправить если очень хочется))
Но опять же зачем практиковаться с этим)) вопрос. 

С ORM масса проблем всегда, когда проекты разрастаются... поэтому в go их не очень любят)

2024-09-02 17:19 UTC, stxreocoma commented on handlers/handlers.go
> +	result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler WHERE id = ? LIMIT 1", id).First(&task)
Хорошо, думал просто что ORM наоборот часто используются

2024-09-02 17:23 UTC, stxreocoma commented on cmd/main.go
> +	app.Listen(":" + os.Getenv("TODO_PORT"))
Так это же одно из заданий со звездочкой

2024-09-02 17:45 UTC, stxreocoma commented on handlers/handlers.go
> +	result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler WHERE id = ? LIMIT 1", id).First(&task)
Стоит ли вообще убрать gorm? Или можно оставить? Я планировал указывать этот проект в резюме...

2024-09-04 17:39 UTC, dirtymew requested changes
Привет Глеб

падают тесты - нужно чтобы проходили

и будем считать проект выполненым

2024-09-04 17:39 UTC, dirtymew commented on cmd/main.go
> +	log.Println(os.Getenv("TODO_PORT"))
зачем еще раз делать долгий запрос к os можно просто log.Println(port) - и на 15 строке

2024-09-04 17:39 UTC, dirtymew commented on database/database.go
> +	log.Println(err.Error())
тут будет паника если нет ошибки - нужно исправить

2024-09-04 17:39 UTC, dirtymew commented on utils/sort.go
> +package utils
на будущее utils/tools/helpers -  считается плохим стилем

лучше пакеты выделять и называть по функционалу и не сваливать все в кучу

2024-09-04 20:08 UTC, stxreocoma commented
> Привет Глеб
> 
> падают тесты - нужно чтобы проходили
> 
> и будем считать проект выполненым

У меня все тесты проходит, и при обычном запуске и через контейнер

2024-09-04 20:14 UTC, stxreocoma commented on utils/sort.go
> +package utils
Стоит ли utils делить на два пакета и как лучше назвать в таком случае?

2024-09-04 20:15 UTC, stxreocoma commented on utils/sort.go
> +package utils
И стоит ли вообще переписать без gorm, либо наоборот все под него переделать?

2024-09-07 11:56 UTC, dirtymew approved these changes
Глеб

задание считаю выполненным - хотя есть пространство для улучшения

Поздравляю и желаю удачи

2024-09-07 11:56 UTC, dirtymew commented on handlers/get.go
> +		result := database.Gorm.Db.Raw("SELECT id, date, title, comment, repeat FROM scheduler LIMIT 50").Limit(50).Find(&tasks)
LIMIT 50 их запроса тогда нужно убрать?

2024-09-07 11:56 UTC, dirtymew commented on utils/sort.go
> +package utils
utils да можно разделить и если что-то не переиспользуется то лучше по месту обьявлять

использовать или нет что-то это твой выбор

2024-09-07 11:56 UTC, dirtymew commented on cmd/main.go
> +	app.Listen(":" + os.Getenv("TODO_PORT"))
я мб не очень подробно описал что имею ввиду

про то что если значение переменной не указано то использовать какое-то значение по умолчанию

2024-09-07 11:56 UTC, dirtymew commented on database/database.go
> +	Gorm.Db, err = gorm.Open(sqlite.Open("scheduler.db"), &gorm.Config{})
вот тут помарка не используешь переменную dbFile @stxreocoma

2024-09-08 14:51 UTC, stxreocoma commented
> Глеб
> 
> задание считаю выполненным - хотя есть пространство для улучшения
> 
> Поздравляю и желаю удачи

Спасибо

2024-09-10 16:31 UTC, merged